# Generated by Django 3.1.3 on 2020-12-16 07:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201216_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article_thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Maximum of 1'),
        ),
    ]
