# Generated by Django 3.1.3 on 2020-12-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_featuredposts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredposts',
            options={'ordering': ['-posted_date'], 'verbose_name_plural': 'Featured Posts'},
        ),
    ]
