# Generated by Django 3.1.3 on 2021-01-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_grid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grid',
        ),
        migrations.DeleteModel(
            name='PastorsQuote',
        ),
    ]
